### numpy random

In [1]:
from numpy import random
print(random.randint(1,100))
print(random.rand())

43
0.8205272072598239


In [5]:
##creating n d arrays
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[21 71 10]
[[ 0 64 96 84]
 [63 29 74 18]
 [15 59 92 68]]
[[[14 10]
  [35 72]
  [31 91]
  [13 36]]

 [[ 3 60]
  [56 79]
  [51 72]
  [63  5]]

 [[16 56]
  [86 43]
  [75 51]
  [13 58]]]


In [7]:
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.5975226749849806
[0.8738445  0.47379176 0.89448197]
[[0.35171804 0.4541929  0.15061638]
 [0.06243454 0.70814458 0.11727771]]


In [11]:
a=random.randint(100,size=(3,2)).ravel()
a

array([27, 36, 21, 70, 51,  9])

In [12]:
random.choice(a)

21

In [13]:
random.choice([1,2,3,4,5],size=(3,4))

array([[3, 1, 4, 1],
       [4, 1, 2, 2],
       [1, 2, 1, 5]])

## Pandas
1. Data manipulation,analysis and cleaning
2. Tabular,Unlabelled

### Creating a data frame
1. using 2 dictionaries
2. simple dictionary to dataframe
3. using series
4. csv file

In [17]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data = {"First":dict1,"Second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [18]:
#simple dict to dataframe
d1 = {"name":["maansi","mounika","sumathi"],"address":["hyd","adb","AP"]}
df1 = pd.DataFrame(d1)
df1

name address
0   maansi     hyd
1  mounika     adb
2  sumathi      AP

In [20]:
#Using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,45.3,45.6,67.8,78.9,89.9,90.9,56.4,66.6])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.60       d
4        5    67.80       e
5        6    78.90       f
6        7    89.90       g
7        8    90.90       h
8        9    56.40       i
9       10    66.60       j

#### Selecting the data from the DataFrame
1. loc
2. iloc

In [22]:
df3["column2"]

0    12.23
1    23.34
2    45.30
3    45.60
4    67.80
5    78.90
6    89.90
7    90.90
8    56.40
9    66.60
Name: column2, dtype: float64

In [23]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    45.30       c
3    45.60       d
4    67.80       e
5    78.90       f
6    89.90       g
7    90.90       h
8    56.40       i
9    66.60       j

In [24]:
df3.loc[:,"column1"] #single column

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [26]:
df3.loc[:,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.60
4        5    67.80
5        6    78.90
6        7    89.90
7        8    90.90
8        9    56.40
9       10    66.60

In [27]:
df3.loc[::-1,["column1","column2"]]  #reverse

column1  column2
9       10    66.60
8        9    56.40
7        8    90.90
6        7    89.90
5        6    78.90
4        5    67.80
3        4    45.60
2        3    45.30
1        2    23.34
0        1    12.23

In [28]:
df3.loc[0:5,["column1","column2"]]  

column1  column2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.60
4        5    67.80
5        6    78.90

In [29]:
df3.loc[2:5,["column1","column2"]]  

column1  column2
2        3     45.3
3        4     45.6
4        5     67.8
5        6     78.9

In [30]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [31]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### Retrieving the info of DataFrame

In [32]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [33]:
df3.shape

(10, 3)

In [34]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [35]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data from DataFrame
1. sample()
2. head()
3. tail()

In [36]:
df3.head()

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.60       d
4        5    67.80       e

In [39]:
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c

In [38]:
df3.tail()

column1  column2 column3
5        6     78.9       f
6        7     89.9       g
7        8     90.9       h
8        9     56.4       i
9       10     66.6       j

In [41]:
df3.tail(2)

column1  column2 column3
8        9     56.4       i
9       10     66.6       j

In [42]:
df3.sample()   ###like random

column1  column2 column3
3        4     45.6       d

In [43]:
df3.sample(2)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b

In [46]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  57.697000
std     3.02765  26.498911
min     1.00000  12.230000
25%     3.25000  45.375000
50%     5.50000  61.500000
75%     7.75000  76.125000
max    10.00000  90.900000

In [49]:
df3 = df3.rename(columns={"column1":"First",
                        "column2":"Second",
                        "column3":"Third"})
df3                     ###Renaming the columns

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.60     d
4      5   67.80     e
5      6   78.90     f
6      7   89.90     g
7      8   90.90     h
8      9   56.40     i
9     10   66.60     j