In [5]:
#1-dimensional array
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
a.shape

(5,)

In [7]:
#2-dim
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a1.shape

(3, 3)

In [9]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a1.ndim

2

In [11]:
a2.ndim

2

In [16]:
#inserting element into array dynamically
a3 = np.array([],dtype="int32")

In [17]:
a3 = np.append(a3,int(input()))
a3

12


array([12])

In [18]:
a3 = np.append(a3,[23,34,45,56])
a3

array([12, 23, 34, 45, 56])

In [19]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### slicing

In [20]:
print(a3[3])

45


In [21]:
#row n coloumn
print(a2[1,1])

5


In [22]:
#range of rows
print(a2[2:,:])

[[7 8 9]]


In [23]:
print(a2[2:,0:2])

[[7 8]]


In [25]:
print(a2[0,0:2])

[1 2]


### Indexing with boolean array

In [26]:
arr1 = np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [27]:
result = (arr1 % 2 == 0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [28]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Appending array

In [29]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
print(arr2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [32]:
# append above
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))         ### vertial stacking

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [33]:
print(np.hstack((arr1,arr2)))     ### horizontal

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes:
1.size
2. itemsize
3. dtype
4. ndim
5. shape

In [34]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


### Functions
1. zeros()
2. ones()
3. full()
4. eye()
5. arange()
6. linspace()
7. reshape()
8. ravel()

In [36]:
z = np.zeros((2,3),dtype="int32")
z

array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
o = np.ones((3,3),dtype="int32")
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [39]:
f = np.full((2,2),"maansi")
f

array([['maansi', 'maansi'],
       ['maansi', 'maansi']], dtype='<U6')

In [40]:
e = np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [41]:
l = np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [42]:
a = np.arange(1,11,2) #similar to range
a

array([1, 3, 5, 7, 9])

In [48]:
print(np.array(a.flat))
print(a.ravel())

[1 3 5 7 9]
[1 3 5 7 9]


### Functions
1. min()
2. max()
3. sum()
4. sqrt()
5. mean()
6. median()
7. std()

In [49]:
a

array([1, 3, 5, 7, 9])

In [52]:
print(a1.sum())
print(a1.sum(axis=1))
print(a1.sum(axis=0))

45
[ 6 15 24]
[12 15 18]


In [54]:
print(a.min())
print(a.max())

1
9


In [55]:
np.sqrt(a)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ])

In [57]:
np.mean(a)

5.0

In [58]:
np.median(a)

5.0

In [59]:
np.std(a)  #standard deviation

2.8284271247461903

### Mathematical operations:
```+,-,*,/,%```

In [64]:
#Create 2 arrays with different values and use =,-,*,/,% on those arrays
arr1 = np.arange(1,11)
arr2 = np.arange(11,21)
print(arr1+arr2)
print(arr2-arr1)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)

[12 14 16 18 20 22 24 26 28 30]
[10 10 10 10 10 10 10 10 10 10]
[ 11  24  39  56  75  96 119 144 171 200]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10]


### dot() --> matrix multiplication
arr1 = m X n
arr2 = n X l

In [74]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [72]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Aplying user-defined function:

In [67]:
list1 = list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [69]:
#1/(1+1) --> x/(x+1)
result = [x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [71]:
f = np.vectorize(lambda x : x/(x+1))
f(a)

array([0.5       , 0.75      , 0.83333333, 0.875     , 0.9       ])